name: reserve
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - arviz
  - cmdstan
  - cmdstanpy[all]
  - jupyterlab
  - cmake
  - pkg-config
  - radian
  - r-base
  - r-renv
  # - r-languageserver
  # - r-httpgd
  # - r-data.table
  # - r-cmdstanr
  # - r-bayesplot
  # - r-brms
  # - r-shinystan
  # - r-showtext
  # - r-showtextdb

